-- Explicit projections: no bank numbers, encrypted KYC, provider payloads, or tokens.
CREATE VIEW public.admin_workspace_records WITH (security_invoker=true) AS
SELECT 'merchants'::text AS section,r.id,CASE WHEN r.status='suspended' THEN 'suspended' ELSE r.registration_state::text END AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',CASE WHEN r.status='suspended' THEN 'suspended' ELSE r.registration_state::text END,
 'name',r.business_name,
 'legalName',r.business_name,
 'storeSlug',r.slug,
 'email',r.contact_email,
 'phone',r.contact_phone,
 'address',concat_ws(', ',r.address,r.lga,r.state),
 'registrationState',r.registration_state,
 'sellingStatus',r.status,
 'submittedAt',v.updated_at,
 'registrationNumber',v.cac_number) AS record FROM public.merchants r LEFT JOIN LATERAL (SELECT cac_number,updated_at FROM public.merchant_verifications WHERE merchant_id=r.id ORDER BY updated_at DESC LIMIT 1) v ON true WHERE true
UNION ALL
SELECT 'catalogue'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'title',r.title,
 'description',r.description,
 'brand',r.brand,
 'condition',r.condition,
 'priceMinor',r.base_price_minor::text,
 'merchantId',r.merchant_id,
 'merchantName',m.business_name,
 'categoryName',c.name,
 'categoryId',r.category_id,
 'sku',i.sku,
 'stock',coalesce(i.stock,0),
 'rejectionReason',r.rejection_reason,
 'submittedAt',r.updated_at) AS record FROM public.products r JOIN public.merchants m ON m.id=r.merchant_id LEFT JOIN public.categories c ON c.id=r.category_id LEFT JOIN LATERAL (SELECT min(v.sku) sku,sum(coalesce(l.available_quantity,0))::int stock FROM public.product_variants v LEFT JOIN public.inventory_levels l ON l.variant_id=v.id WHERE v.product_id=r.id) i ON true WHERE true
UNION ALL
SELECT 'orders'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'reference',r.order_number,
 'customerId',r.buyer_id,
 'customerName',p.full_name,
 'merchantId',r.merchant_id,
 'merchantName',m.business_name,
 'totalMinor',r.total_amount_minor::text,
 'subtotalMinor',r.subtotal_minor::text,
 'deliveryFeeMinor',r.delivery_fee_minor::text,
 'paymentStatus',pay.status,
 'carrier',s.carrier,
 'trackingNumber',s.tracking_code,
 'shippingAddress',r.delivery_address,
 'deliveredAt',s.delivered_at,
 'returnDeadline',r.return_window_ends_at,
 'shipmentStatus',s.status) AS record FROM public.orders r JOIN public.profiles p ON p.id=r.buyer_id JOIN public.merchants m ON m.id=r.merchant_id LEFT JOIN public.shipments s ON s.order_id=r.id LEFT JOIN LATERAL (SELECT status FROM public.payment_attempts WHERE order_id=r.id ORDER BY created_at DESC LIMIT 1) pay ON true WHERE true
UNION ALL
SELECT 'customers'::text AS section,r.id,CASE WHEN c.deletion_requested_at IS NOT NULL THEN 'deletion_requested' WHEN c.restricted THEN 'restricted' ELSE 'active' END AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',CASE WHEN c.deletion_requested_at IS NOT NULL THEN 'deletion_requested' WHEN c.restricted THEN 'restricted' ELSE 'active' END,
 'name',r.full_name,
 'email',r.email,
 'phone',r.phone,
 'deletionRequestedAt',c.deletion_requested_at,
 'privacyReviewStartedAt',c.privacy_review_started_at,
 'orderCount',n.count,
 'totalMinor',n.total) AS record FROM public.profiles r LEFT JOIN public.admin_customer_controls c ON c.id=r.id LEFT JOIN LATERAL (SELECT count(*)::int count,coalesce(sum(total_amount_minor) FILTER(WHERE status NOT IN ('pending_payment','cancelled')),0)::text total FROM public.orders WHERE buyer_id=r.id) n ON true WHERE true
UNION ALL
SELECT 'returns'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'reference','RET-'||left(r.id::text,8),
 'reason',r.reason,
 'merchantResponse',r.decision_note,
 'orderId',r.order_id,
 'customerId',r.buyer_id,
 'customerName',p.full_name,
 'merchantId',r.merchant_id,
 'merchantName',m.business_name,
 'amountMinor',o.subtotal_minor::text,
 'requestedAt',r.created_at,
 'returnDeadline',o.return_window_ends_at,
 'refundId',rv.id) AS record FROM public.return_requests r JOIN public.orders o ON o.id=r.order_id JOIN public.merchants m ON m.id=o.merchant_id JOIN public.profiles p ON p.id=o.buyer_id LEFT JOIN public.admin_refund_reviews rv ON rv.return_id=r.id WHERE true
UNION ALL
SELECT 'disputes'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'reference','CASE-'||left(r.id::text,8),
 'reason',r.reason,
 'orderId',r.order_id,
 'customerId',o.buyer_id,
 'customerName',p.full_name,
 'merchantId',o.merchant_id,
 'merchantName',m.business_name,
 'amountMinor',o.subtotal_minor::text,
 'returnId',r.return_id,
 'resolutionNote',r.resolution_note,
 'outcome',r.status,
 'refundId',rv.id) AS record FROM public.disputes r JOIN public.orders o ON o.id=r.order_id JOIN public.merchants m ON m.id=o.merchant_id JOIN public.profiles p ON p.id=o.buyer_id LEFT JOIN public.admin_refund_reviews rv ON rv.dispute_id=r.id WHERE true
UNION ALL
SELECT 'support'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'subject',r.subject,
 'category',r.category,
 'customerId',r.user_id,
 'customerName',p.full_name,
 'orderId',r.order_id,
 'merchantId',o.merchant_id) AS record FROM public.support_tickets r JOIN public.profiles p ON p.id=r.user_id LEFT JOIN public.orders o ON o.id=r.order_id WHERE true
UNION ALL
SELECT 'refunds'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'reference','REF-'||left(r.id::text,8),
 'orderId',r.order_id,
 'customerId',o.buyer_id,
 'customerName',p.full_name,
 'merchantId',o.merchant_id,
 'merchantName',m.business_name,
 'amountMinor',r.amount_minor::text,
 'reason',r.reason,
 'providerReference',r.provider_ref_code) AS record FROM public.refunds r JOIN public.orders o ON o.id=r.order_id JOIN public.merchants m ON m.id=o.merchant_id JOIN public.profiles p ON p.id=o.buyer_id WHERE true
UNION ALL
SELECT 'refunds'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'reference','REVIEW-'||left(r.id::text,8),
 'orderId',r.order_id,
 'customerId',o.buyer_id,
 'customerName',p.full_name,
 'merchantId',o.merchant_id,
 'merchantName',m.business_name,
 'amountMinor',r.amount_minor::text,
 'reason',r.reason,
 'requestedBy',r.requested_by,
 'returnId',r.return_id,
 'disputeId',r.dispute_id) AS record FROM public.admin_refund_reviews r JOIN public.orders o ON o.id=r.order_id JOIN public.merchants m ON m.id=o.merchant_id JOIN public.profiles p ON p.id=o.buyer_id WHERE r.refund_id IS NULL
UNION ALL
SELECT 'payouts'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'reference','PAY-'||left(r.id::text,8),
 'merchantId',r.merchant_id,
 'merchantName',m.business_name,
 'amountMinor',r.amount_minor::text,
 'bankName',b.bank_name,
 'accountName',b.account_name,
 'accountLast4',right(b.account_number,4),
 'requestedBy',r.requested_by,
 'requestedByName',p.full_name,
 'approvedByName',a.full_name,
 'providerReference',r.provider_reference) AS record FROM public.payouts r JOIN public.merchants m ON m.id=r.merchant_id JOIN public.merchant_bank_accounts b ON b.id=r.bank_account_id LEFT JOIN public.profiles p ON p.id=r.requested_by LEFT JOIN public.profiles a ON a.id=r.approved_by WHERE true
UNION ALL
SELECT 'reconciliation'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'reference',r.provider_reference,
 'providerReference',r.provider_reference,
 'orderId',r.order_id,
 'payoutId',r.payout_id,
 'providerAmountMinor',r.provider_amount_minor::text,
 'ledgerAmountMinor',r.ledger_amount_minor::text,
 'reason',r.reason,
 'lastCheckedAt',r.last_checked_at) AS record FROM public.admin_reconciliation r  WHERE true
UNION ALL
SELECT 'content'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'title',r.title,
 'placement',r.placement,
 'targetType',r.target_type,
 'targetId',r.target_id,
 'imageUrl',r.image_url,
 'altText',r.alt_text,
 'priority',r.priority,
 'startsAt',r.starts_at,
 'endsAt',r.ends_at) AS record FROM public.admin_campaigns r  WHERE true
UNION ALL
SELECT 'access'::text AS section,r.id,coalesce(a.status,'active') AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',coalesce(a.status,'active'),
 'name',r.full_name,
 'email',r.email,
 'roles',coalesce(rr.roles,'{}'::text[])) AS record FROM public.profiles r LEFT JOIN public.admin_staff_access a ON a.id=r.id LEFT JOIN LATERAL (SELECT array_agg(role::text ORDER BY role) roles FROM public.user_roles WHERE user_id=r.id AND role::text=ANY(ARRAY['operations_admin','security_admin','support_agent','catalogue_moderator','finance_reviewer'])) rr ON true WHERE rr.roles IS NOT NULL OR a.status='revoked'
UNION ALL
SELECT 'access'::text AS section,r.id,r.status::text AS status,r.created_at AS created_at,r.updated_at AS updated_at,r.admin_version::text AS version,jsonb_build_object('id',r.id,
 'version',r.admin_version::text,
 'createdAt',r.created_at,
 'updatedAt',r.updated_at,
 'status',r.status::text,
 'email',r.email,
 'roles',r.roles,
 'invitedByName',p.full_name,
 'expiresAt',r.expires_at,
 'deliveredAt',r.delivered_at,
 'invitation',true) AS record FROM public.admin_invitations r JOIN public.profiles p ON p.id=r.invited_by WHERE r.status IN ('invited','expired','revoked')
UNION ALL
SELECT 'audit'::text AS section,r.id,'recorded'::text AS status,r.created_at AS created_at,r.created_at AS updated_at,'1'::text AS version,jsonb_build_object('id',r.id,
 'version','1'::text,
 'createdAt',r.created_at,
 'updatedAt',r.created_at,
 'status','recorded'::text,
 'title',r.action,
 'action',r.action,
 'actorName',p.full_name,
 'resourceType',r.resource_type,
 'resourceId',r.resource_id,
 'note',r.metadata->>'note',
 'requestId',r.metadata->>'requestId') AS record FROM public.audit_events r LEFT JOIN public.profiles p ON p.id=r.actor_id WHERE true;
REVOKE ALL ON public.admin_workspace_records FROM anon,authenticated;
GRANT SELECT ON public.admin_workspace_records TO service_role;
